<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="website">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="header">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="h1" type="xs:string"/>
                            <xs:element name="nav">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ul">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="li" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="a" type="xs:string"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="main">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="container">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="about-section">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="h2" type="xs:string"/>
                                                    <xs:element name="p" maxOccurs="unbounded" type="xs:string"/>
                                                    <xs:element name="mission">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="h3" type="xs:string"/>
                                                                <xs:element name="p" type="xs:string"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="footer">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="about">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="h3" type="xs:string"/>
                                        <xs:element name="p" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="links">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="h3" type="xs:string"/>
                                        <xs:element name="p" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="other">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="h3" type="xs:string"/>
                                        <xs:element name="p" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
</xs:schema>
