<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="loginPage">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="form">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="title" type="xs:string"/>
                            <xs:element name="fields">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="field" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="type" type="xs:string"/>
                                                    <xs:element name="placeholder" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="options">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="checkbox" type="xs:string"/>
                                        <xs:element name="link" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="button" type="xs:string"/>
                            <xs:element name="register">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="message" type="xs:string"/>
                                        <xs:element name="link" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>
