# Generated by Django 6.0.6 on 2026-07-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(choices=[('beauty_skincare', 'Beauty'), ('fashion_men', 'Fashion'), ('electronics_mobile', 'Electronics'), ('home_kitchen', 'Home'), ('sports_fitness', 'Sports')], max_length=255),
        ),
    ]
