# Generated by Django 6.0.6 on 2026-07-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('beauty_skincare', 'Beauty'), ('fashion_men', 'Fashion'), ('electronics_mobile', 'Electronics'), ('home_kitchen', 'Home'), ('sports_fitness', 'Sports')], default='uncategorized', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
