# Generated by Django 6.0.6 on 2026-07-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_alter_product_category_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics_gaming', 'Electronics'), ('electronics_mobile', 'Electronics'), ('electronics_camera', 'Electronics'), ('apparel', 'Fashion'), ('footwear', 'Fashion'), ('bags', 'Fashion'), ('fashion_accessories', 'Fashion'), ('beauty_skincare', 'Beauty'), ('furniture_home', 'Home'), ('kitchen_dining', 'Home'), ('sports_outdoors', 'Sports'), ('vehicles', 'Vehicles'), ('food_beverage', 'Food & Beverage'), ('other', 'Other')], default='uncategorized', max_length=50),
        ),
    ]
